#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_PAGE_SPY_PORT text "Port" 8080

  service::config_set SERVICE_PAGE_SPY_SECRET_KEY text "Secret Key" $(os::uuid)

  service::config_set SERVICE_PAGE_SPY_DOREAMON_CLIENT_ID text "Doreamon Client ID"
  service::config_set SERVICE_PAGE_SPY_DOREAMON_CLIENT_SECRET text "Doreamon Client SECRET"
  service::config_set SERVICE_PAGE_SPY_DOREAMON_REDIRECT_URI text "Doreamon Redirect URI"
}

check $@
