services:
  page-spy:
    restart: always
    image: whatwewant/page-spy:${SERVICE_PAGE_SPY_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_PAGE_SPY_PORT}:6752
      
networks:
  default:
    external: true
    name: compose-ingress
